// frontend/src/AQIMeter.tsx
import { Component, createMemo } from 'solid-js';
import { AQItoDesc } from './aqi_calculations';

interface AQIMeterProps {
    aqi: number;
}

const AQIMeter: Component<AQIMeterProps> = (props) => {
    const aqiDescription = createMemo(() => AQItoDesc(props.aqi));

    return (
        <div
            class="aqi-container"
            style={{
                "text-align": "center",
                "background-color": aqiDescription().color
            }}
        >
            <span class="aqi_text">
                {aqiDescription().text} {isNaN(props.aqi) ? '' : props.aqi}
            </span>
            <div class="meter">
                <div
                    style={{ width: `${aqiDescription().percent}%` }}
                    class="percent"
                ></div>
            </div>
        </div>
    );
};

export default AQIMeter;

// svelte-frontend/src/AQIMeter.svelte
<script>
	export let aqi;

	import {AQItoDesc} from './aqi_calculations';

	$: aqi_description = AQItoDesc(aqi);

</script>

<div id="aqi-container" style="text-align: center; background-color: {aqi_description.color}">
	<span id="aqi_text">{aqi_description.text} {isNaN(aqi) ? '': aqi }</span>
	<div class="meter">
		<div style="width: {aqi_description.percent}%" id="percent"></div>
	</div>
</div>

<style>
	#aqi-container {
		color: white;
		padding: 16px;
		border-radius: 16px;
		/* max-width: 400px; */
		width: 100%;
		box-sizing: border-box;
		overflow: hidden;
	}

	.meter { 
		height: 12px;
		margin-top: 4px;
		position: relative;
		background: rgba(0, 0, 0, 0.11);
		width: calc(100% + 32px);
		padding: 0px;
		box-sizing: border-box;
		margin-left: -16px;
		margin-bottom: -16px;
	}
	.meter > div {
		display: block;
		height: 100%;
		background-color: rgba(0, 0, 0, 0.5);
		position: relative;
	}

</style>
